# Generated by Django 4.2.5 on 2023-09-16 13:23

from django.db import migrations, models
import django.db.models.deletion
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='task_due_date',
            field=models.DateTimeField(default=todo.models.one_week_hence),
        ),
        migrations.AddField(
            model_name='task',
            name='task_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='todo.category'),
        ),
    ]
